---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Google Chrome.app
    - /Applications/iTerm.app
    - /Applications/Sublime Text.app
    folders:
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-source-code-pro
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git_config
    git_user_name: Damien Metzler
    git_user_email: dmetzler@nuxeo.com
  - role: brew_package
    package_name: git
  - role: legit
  - role: hub
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: spectacle
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: slack
  # Same a spectacle but not opensource
  #- role: cask_package
  #  package_name: divvy
  - role: cask_package
    package_name: jumpcut
  #- role: brew_package
  #  package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: npm_package
    package_name: grunt-cli  
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: go

  ## vms
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: dockertoolbox


  #- role: brew_package
  #  package_name: android-sdk
  ## databases
  - role: cask_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb
  - role: brew_package
    package_name: elasticsearch
  ## deployment
  #- role: brew_package
  #  package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: sublime-text
  - role: cask_package
    package_name: eclipse-jee

  - role: brew_package
    package_name: maven

  ## browsers
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: chromium

  ## Other
  - role: cask_package
    package_name: plex-home-theater
  - role: cask_package
    package_name: 1password
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: textexpander
  - role: cask_package
    package_name: tunnelblick 
  - role: cask_package
    package_name: bartender
  - role: cask_package
    package_name: google-drive
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: mumble
  - role: cask_package
    package_name: ios7-screensaver
  - role: cask_package    
    package_name: openoffice
  - role: cask_package    
    package_name: deezer
  - role: cask_package    
    package_name: disk-invetory-x
  - role: cask_package    
    package_name: mou
  - role: brew_package
    package_name: graphviz
  - role: brew_package
    package_name: imagemagick
  - role: cask_package
    package_name: pgadmin3
  - role: cask_package
    package_name: adobe-reader
  - role: cask_package
    package_name: gitup


  

